
import { Inter } from "next/font/google";
import Link from "next/link";
import "bootstrap/dist/css/bootstrap.min.css"; 
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="my-6 ">
          <div className="d-flex justify-content-center align-items-center">
        <Link class="btn btn-primary text-decorartor-none" href={'/createPost'}>Create Post</Link>
        </div>
        </div>
            {children}
      </body>
    </html>
  );
}
