
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="my-6">
        <Link class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-0 px-4 rounded" href={'/createPost'}>Create Post</Link>
        </div>
            {children}
      </body>
    </html>
  );
}
